# Generated by Django 4.1.6 on 2023-02-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0002_alter_banner_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
