# Generated by Django 4.1.6 on 2023-02-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0003_brand_address_brand_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
