# Generated by Django 4.1.6 on 2023-02-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0004_productattribute_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='image_two',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_two',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/images'),
        ),
    ]
