# Generated by Django 4.1.6 on 2023-02-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0006_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='image_four',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='upload_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
