# Generated by Django 4.1.6 on 2023-02-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri_app', '0007_productattribute_image_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
